spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${secret.kakao.client-id}
            client-secret: ${secret.kakao.client-secret}
            scope: profile_nickname, profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  header: token
  issuer: film
  client-secret: dGhpc2lzdGhlc2VjcmV0Y2xpZW50a2V5b2Zwcm9qZWN0ZmlsbWludGVhbTE3VE9Q
  expiry-seconds: 2160000

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    refresh-token-expiry: 604800000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth/redirect
