# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      - main
      - develop
      
env:
  S3_BUCKET_NAME: iyj-web

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Copy S3 secret
      env: 
        AWS_S3_SECRET: ${{ secrets.AWS_S3_CREDENTIALS }}
        SECRET_DIR: film-external/src/main/resources
        SECRET_FILE_NAME: application-aws.yml
      run: echo $AWS_S3_SECRET | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME    
      
    - name: Copy OAUTH2 secret
      env:
        OAUTH2_SECRET: ${{ secrets.OAUTH2_SECRET }}
        SECRET_DIR: film-api/src/main/resources
        SECRET_FILE_NAME: application-secret.yml
      run: echo $OAUTH2_SECRET | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean build -p ./film-api
      
    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
      
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name film \
        --deployment-group-name film-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip \
        --region ap-northeast-2
